### ISSUE TITLE
Have option to specify TCP or UDP for exposing ports

### ISSUE THREAD

**Issue by urosgruber** [pizzamig/pot#115]
I sometimes need to set up redirect for UDP and not just TCP. I started working on a patch for this but I would like to fist understand if this is a feature you're willing to include. Idea for how to use it in a command is as follows

`# pot export-ports -p mypot -e tcp:80:8080`

**Comment by pizzamig** [comment]
Hi.
the udp support is a nice feature to add.
I played with it some time ago with `pf`, but for some reasons I had trouble to configure it.

I'm more than happy to review any patch you will submit

**Comment by pizzamig** [comment]
This feature has been implemented, but it's net yet part of any release.
I'll do some deeper testing, before, but I'm confident to release it soon.
The implementation follow your suggestion, with the protocol optionally specified in the argument.
Default value is `tcp`, to not break compatibility.

**Comment by urosgruber** [comment]
What is the best way to test it out since I have installed last version from ports?

**Comment by pizzamig** [comment]
I tested it out and it works, so I'm going to close this issue.
```console
pot udp-test
	disk usage      : 523M
	virtual memory  : 70M
	physical memory : 23M

	Network port redirection
		rdr pass on wlan0 inet proto udp from any to (wlan0) port 53 -> 10.192.0.4 port 53
```
One way to test it is:
* download the repo locally (`$HOME/pot`)
* copy (or link) the `/usr/local/etc/pot/pot.conf` in `$HOME/pot/etc`
* add `$HOME/pot/bin` in front of the PATH environment variable, to pick the local one instead of `/usr/local/bin/pot`
You can verify the $PATH changes with `command -v pot`

It's not yet documented, but `export-ports` works like you suggested

**Comment by urosgruber** [comment]
All looks fine so 👍 and thanks for this new feature.

**Comment by pizzamig** [comment]
Closing the bug, after successful test
