### ISSUE TITLE
Levels are more than two.

### ISSUE THREAD

**Issue by OleM2k** [pizzamig/pot#41]
Pot supported 2 levels.
But I want to test:
- two pots: nginx and apache - first level;
- two pots: mysql and postgresql - second level;
- three pots CMS-s: drupal, joomla, wordpess - third level;
- nine pots whit three sites on each CMS: 1dp,2dp,3dp,1jm,2jm,3jm,1wp,2wp,3wp - fourth level.

Is it possible to solve such a problem with the possibilities of pot?

Grazie!

**Comment by pizzamig** [comment]
Hi.
that scenario is not quite possible, because levels are based on directories. What is in the same directory cannot be in a different level. You can think to levels are "logical disk partitions" that can be mounted to your filesystem.
Currently, there are 3 fixed levels:
1. `/` : the base system
2. `/usr/local` and `/var/db/pkg` : all packages
3. `/etc` `/usr/local/etc` `/usr/home` `/root` and `/var` where everything else

Then, you can have additional "logical disk partitions", called file system components (fscomp) that can be added to you container (and reused by other containers)

An example would be:
1. FreeBSD 11.1
2. nginx + php packages
3. server configuration
4. an additional fscomp where you put the php code

What is not possible, is to split nginx and php, because both of them are packages and some of their files are in the same directory

**Comment by pizzamig** [comment]
I'm closing this issue for now.
This scenario is currently too complicated, because ZFS doesn't support Overlays.
A similar idea will be possible in the future, with images. But it's an idea still in embryonic state.
