### ISSUE TITLE
mount_nullfs says "No such file or directory" and fails to mount when starting a pot

### ISSUE THREAD

**Issue by 0mp** [pizzamig/pot#45]
Here's what I've done:

```
sudo pot init
sudo pot create-base -r 11.2
sudo pot create -p committer-pot -b 11.2
sudo pot create-fscomp -f svn-ports
sudo pot create-fscomp -f svn-src
sudo pot create-fscomp -f svn-doc
sudo pot add-fscomp -p committer-pot -f svn-src -m ~/freebsd/svn/src/
sudo pot add-fscomp -p committer-pot -f svn-ports -m ~/freebsd/svn/ports/
sudo pot add-fscomp -p committer-pot -f svn-doc -m ~/freebsd/svn/doc/
sudo pot snapshot -p committer-pot
sudo pot start committer-pot
```

As a result of the last command I got:

> 
> ```
> mount_nullfs: /opt/pot/jails/committer-pot/m/home: No such file or directory
> ###>  Error mounting /opt/pot/fscomp/svn-src
> ifconfig: interface destroy does not exist
> ###>  Mount failed
> ```

It happens every time I try to run `sudo pot start committer-pot`.

**Comment by 0mp** [comment]
I managed to start a pot with those commands:

```
sudo pot create -p pot0 -b 11.2
sudo pot add-fscomp -p pot0 -f svn-src -m /mnt
sudo pot start pot0
```

**Comment by pizzamig** [comment]
I'm able to reproduce the error.
The problem is the expansion of `~` , that happen outside the container, so it would try to use the `$HOME` of the current user.
The real problem, here, is that it's quite hard to validate the argument of the `-m` option
If you use an existing absolute pathname (like `/mnt`) you are fine, but there is room from improvement for sure
